services:
  - type: web
    name: crowd-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir torch==2.1.2+cpu torchvision==0.16.2+cpu --index-url https://download.pytorch.org/whl/cpu
      pip install --no-cache-dir -r requirements.txt
      npm install
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
