services:
  - type: web
    name: crowd-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      npm install
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
